import React, { useEffect } from 'react';
import { BackgroundCircles } from '../components/ui/background-circles';
import { SEOHead } from '../components/seo/SEOHead';
import { Link } from 'react-router-dom';

export const TermsOfServicePage: React.FC = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    const lastUpdated = "February 20, 2026";

    return (
        <div className="min-h-screen bg-shinto-white font-serif text-jap-indigo relative">
            <SEOHead
                title="Terms of Service | Street Spirit"
                description="Terms of Service and legal disclaimers for using the Street Spirit application."
                path="/terms"
            />
            <div className="absolute inset-0 z-0 pointer-events-none opacity-20 fixed">
                <BackgroundCircles variant="primary" />
            </div>

            <div className="relative z-10 pt-24 px-4 pb-12 max-w-3xl mx-auto flex flex-col items-center">
                <div className="text-center mb-12">
                    <span className="text-jap-vermilion font-bold tracking-[0.3em] uppercase text-xs mb-2 block">
                        LEGAL COMPLIANCE
                    </span>
                    <h1 className="text-4xl md:text-5xl font-brush font-normal text-jap-indigo tracking-widest">
                        Terms of Service
                    </h1>
                    <div className="text-xs text-gray-500 mt-4 tracking-widest uppercase">
                        Last Updated: {lastUpdated}
                    </div>
                    <div className="w-16 h-1 bg-jap-gold-300 mx-auto mt-6"></div>
                </div>

                <div className="bg-white/80 backdrop-blur-sm border border-gray-200 p-8 md:p-12 shadow-xl rounded-sm w-full prose prose-stone max-w-none">
                    <p className="lead text-lg mb-8 italic text-gray-600 border-l-4 border-jap-gold-300 pl-4">
                        Please read these Terms of Service carefully before using the Street Spirit website (the "Service") operated by its creators ("us", "we", or "our"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.
                    </p>

                    <h2 className="text-xl font-bold text-jap-indigo mt-8 mb-4 border-b border-gray-200 pb-2">1. Nature of the Service (Entertainment Purposes Only)</h2>
                    <p className="mb-4">
                        Street Spirit is an interactive, digital art project and entertainment service designed to simulate a cyberpunk-infused shrine experience.
                    </p>
                    <p className="mb-6 p-4 bg-gray-100 border-l-4 border-jap-vermilion text-gray-800 font-bold">
                        IMPORTANT DISCLAIMER: The spiritual advice, fortunes (Omikuji), insights, and any text or images generated by this Service are created by Artificial Intelligence (AI). They are for ENTERTAINMENT PURPOSES ONLY.
                    </p>
                    <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                        <li>The outputs are algorithmic generations and do not constitute professional, medical, legal, financial, or psychological advice.</li>
                        <li>You should never make important life decisions based on the content generated by this Service.</li>
                        <li>We assume <strong>zero responsibility or liability</strong> for any physical, emotional, or financial consequences resulting from your use of, or reliance on, the Service.</li>
                    </ul>

                    <h2 className="text-xl font-bold text-jap-indigo mt-8 mb-4 border-b border-gray-200 pb-2">2. Payments and Offerings</h2>
                    <p className="mb-4">Certain features of the Service (such as receiving an Oracle/Omikuji) may require a digital "Offering" (payment) after a free trial limit is reached. We operate on a "Pay What You Want" model for some features.</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                        <li><strong>Payment Processor:</strong> All financial transactions are securely handled by our third-party payment processor (Stripe). We do not collect or store your payment card details.</li>
                        <li><strong>Refund Policy:</strong> Due to the digital and immediate nature of the AI-generated content provided, all "Offerings" (payments) are considered final and <strong>NON-REFUNDABLE</strong> once the oracle generation process has begun.</li>
                        <li><strong>Virtual Items:</strong> Virtual items (like Goshuin stamps or Ema) hold no real-world monetary value and cannot be exchanged for cash.</li>
                    </ul>

                    <h2 className="text-xl font-bold text-jap-indigo mt-8 mb-4 border-b border-gray-200 pb-2">3. User Conduct and Content</h2>
                    <p className="mb-4">When using interactive features like the "Ema (Wishing Plaque)" wall, you are solely responsible for the content you submit. You agree not to post content that is:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                        <li>Illegal, threatening, defamatory, abusive, harassing, degrading, intimidating, fraudulent, deceptive, or invasive of another's privacy.</li>
                        <li>Infringing on any trademark, patent, trade secret, copyright, or other proprietary right of any party.</li>
                    </ul>
                    <p className="mb-4">We reserve the right, but have no obligation, to remove any content that we determine in our sole discretion violates these Terms.</p>

                    <h2 className="text-xl font-bold text-jap-indigo mt-8 mb-4 border-b border-gray-200 pb-2">4. Intellectual Property</h2>
                    <p className="mb-6 text-gray-700">
                        The Service and its original content (excluding User Content and specific AI-generated responses which you may keep for personal use), features, and functionality are and will remain the exclusive property of Street Spirit's creators and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.
                    </p>

                    <h2 className="text-xl font-bold text-jap-indigo mt-8 mb-4 border-b border-gray-200 pb-2">5. Limitation of Liability</h2>
                    <p className="mb-6 text-gray-700">
                        IN NO EVENT SHALL STREET SPIRIT, ITS CREATORS, DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (III) ANY CONTENT OBTAINED FROM THE SERVICE; AND (IV) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.
                    </p>

                    <h2 className="text-xl font-bold text-jap-indigo mt-8 mb-4 border-b border-gray-200 pb-2">6. Changes to Terms</h2>
                    <p className="mb-6 text-gray-700">
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
                    </p>

                    <div className="mt-12 text-center">
                        <Link to="/" className="inline-block px-8 py-3 bg-jap-indigo text-white font-bold tracking-widest hover:bg-jap-vermilion transition-colors shadow-lg rounded-sm text-sm">
                            I UNDERSTAND, RETURN
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
};
